#!/usr/bin/env python

# Рекурсивный поиск файлов
import os



x_dir = ''
x_dir = input('Введите директорию поиска в формате "/home/...": ')
x_file = input('Введите разрешение фаила: ')

if x_dir == '':
    x_dir = '/home/'
else: x_dir
path = x_dir
print(path)
for rootdir, dirs, files in os.walk(path):
	for file in files:
		if((file.split('.')[-1])==x_file):
			print(os.path.join(rootdir, file))


